version: 1.0
app:
  instances:
    min: 1
    max: 2
  resources:
    cpu: 1
  version: d1b68588-6789-4cf0-9a63-8a8d2c3654ab
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: DBHost
      value: "ec2-34-204-61-161.compute-1.amazonaws.com"
    - name: DBName
      value: MSGRDB
    - name: DBPort
      value: "60005"
    - name: DBUser
      value: db2inst1
    - name: DBPass
      value: "{aes}AOj0Vd9B/slcxVxQdc7wNhZl6GF2JMy6tMu3hISuxeMExQkNVbzRrxVhKiDxd+MIDA=="
    - name: ldapHost
      value: "ec2-34-204-61-161.compute-1.amazonaws.com"
    - name: ldapPort
      value: "9389"
    - name: ldapSSL
      value: "false"
