version: 1.0
app:
  instances:
    min: 1
    max: 2
  resources:
    cpu: 1
  version: 352d226c-25d3-460e-93f7-061515fdd0e8
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: DBHost
      value: "ec2-34-204-61-161.compute-1.amazonaws.com"
    - name: DBName
      value: MSGRDB
    - name: DBPort
      value: "60005"
    - name: DBUser
      value: db2inst1
    - name: DBPass
      value: "{aes}ALRH2zT5Pk8K7cBSN1qrVIEnU8CTibIH/Lftmq7euqq37f941W2lulAmnROH76CrAg=="
    - name: ldapHost
      value: "ec2-34-204-61-161.compute-1.amazonaws.com"
    - name: ldapPort
      value: "9389"
    - name: ldapSSL
      value: "false"
